window.quotesData = [
  {
    q: "A man is great not because he hasn't failed; a man is great because failure hasn't stopped him.",
    a: "Confucius",
    c: "95",
    h: "<blockquote>&ldquo;A man is great not because he hasn't failed; a man is great because failure hasn't stopped him.&rdquo; &mdash; <footer>Confucius</footer></blockquote>",
  },
  {
    q: "Either write something worth reading or do something worth writing.",
    a: "Benjamin Franklin",
    c: "67",
    h: "<blockquote>&ldquo;Either write something worth reading or do something worth writing.&rdquo; &mdash; <footer>Benjamin Franklin</footer></blockquote>",
  },
  {
    q: "Some people feel the rain. Others just get wet. ",
    a: "Bob Dylan",
    c: "48",
    h: "<blockquote>&ldquo;Some people feel the rain. Others just get wet. &rdquo; &mdash; <footer>Bob Dylan</footer></blockquote>",
  },
  {
    q: "When you believe in a thing, believe in it all the way, implicitly and unquestionable.",
    a: "Walt Disney",
    c: "86",
    h: "<blockquote>&ldquo;When you believe in a thing, believe in it all the way, implicitly and unquestionable.&rdquo; &mdash; <footer>Walt Disney</footer></blockquote>",
  },
  {
    q: "Every limit is a beginning as well as an ending.",
    a: "George Eliot",
    c: "48",
    h: "<blockquote>&ldquo;Every limit is a beginning as well as an ending.&rdquo; &mdash; <footer>George Eliot</footer></blockquote>",
  },
  {
    q: "Do good, live in the most positive and joyful way possible every day.",
    a: "Roy T. Bennett",
    c: "69",
    h: "<blockquote>&ldquo;Do good, live in the most positive and joyful way possible every day.&rdquo; &mdash; <footer>Roy T. Bennett</footer></blockquote>",
  },
  {
    q: "Fortunate are those who take the first steps.",
    a: "Paulo Coelho",
    c: "45",
    h: "<blockquote>&ldquo;Fortunate are those who take the first steps.&rdquo; &mdash; <footer>Paulo Coelho</footer></blockquote>",
  },
  {
    q: "If you do what you've always done, you'll get what you've always gotten.",
    a: "Tony Robbins",
    c: "72",
    h: "<blockquote>&ldquo;If you do what you've always done, you'll get what you've always gotten.&rdquo; &mdash; <footer>Tony Robbins</footer></blockquote>",
  },
  {
    q: "If you do not get the chills when you set your goal you're not setting big enough goals.",
    a: "Bob Proctor",
    c: "88",
    h: "<blockquote>&ldquo;If you do not get the chills when you set your goal you're not setting big enough goals.&rdquo; &mdash; <footer>Bob Proctor</footer></blockquote>",
  },
  {
    q: "The future depends on what you do today. ",
    a: "Mahatma Gandhi",
    c: "41",
    h: "<blockquote>&ldquo;The future depends on what you do today. &rdquo; &mdash; <footer>Mahatma Gandhi</footer></blockquote>",
  },
  {
    q: "Creative people are often found either disagreeable or intimidating by mediocrities.",
    a: "Criss Jami",
    c: "84",
    h: "<blockquote>&ldquo;Creative people are often found either disagreeable or intimidating by mediocrities.&rdquo; &mdash; <footer>Criss Jami</footer></blockquote>",
  },
  {
    q: "Thinking is the hardest work there is, which is probably the reason why so few engage in it.",
    a: "Henry Ford",
    c: "92",
    h: "<blockquote>&ldquo;Thinking is the hardest work there is, which is probably the reason why so few engage in it.&rdquo; &mdash; <footer>Henry Ford</footer></blockquote>",
  },
  {
    q: "Either get busy living or get busy dying.",
    a: "Stephen King",
    c: "41",
    h: "<blockquote>&ldquo;Either get busy living or get busy dying.&rdquo; &mdash; <footer>Stephen King</footer></blockquote>",
  },
  {
    q: "Outstanding people have one thing in common: an absolute sense of mission.  ",
    a: "Zig Ziglar",
    c: "76",
    h: "<blockquote>&ldquo;Outstanding people have one thing in common: an absolute sense of mission.  &rdquo; &mdash; <footer>Zig Ziglar</footer></blockquote>",
  },
  {
    q: "Change is not a four letter word...but often your reaction to it is!",
    a: "Jeffrey Gitomer",
    c: "68",
    h: "<blockquote>&ldquo;Change is not a four letter word...but often your reaction to it is!&rdquo; &mdash; <footer>Jeffrey Gitomer</footer></blockquote>",
  },
  {
    q: "A man is but a product of his thoughts. What he thinks he becomes.",
    a: "Mahatma Gandhi",
    c: "66",
    h: "<blockquote>&ldquo;A man is but a product of his thoughts. What he thinks he becomes.&rdquo; &mdash; <footer>Mahatma Gandhi</footer></blockquote>",
  },
  {
    q: "Being in a good frame of mind helps keep one in the picture of health.",
    a: "Unknown",
    c: "70",
    h: "<blockquote>&ldquo;Being in a good frame of mind helps keep one in the picture of health.&rdquo; &mdash; <footer>Unknown</footer></blockquote>",
  },
  {
    q: "The key to success is action.",
    a: "Brian Tracy",
    c: "29",
    h: "<blockquote>&ldquo;The key to success is action.&rdquo; &mdash; <footer>Brian Tracy</footer></blockquote>",
  },
  {
    q: "Don't talk about what you have done or what you are going to do.",
    a: "Thomas Jefferson",
    c: "64",
    h: "<blockquote>&ldquo;Don't talk about what you have done or what you are going to do.&rdquo; &mdash; <footer>Thomas Jefferson</footer></blockquote>",
  },
  {
    q: "Time and health are two precious assets that we don't recognize and appreciate until they have been depleted. ",
    a: "Denis Waitley",
    c: "110",
    h: "<blockquote>&ldquo;Time and health are two precious assets that we don't recognize and appreciate until they have been depleted. &rdquo; &mdash; <footer>Denis Waitley</footer></blockquote>",
  },
  {
    q: "Becoming a great leader doesn't mean being perfect. it means living with your imperfections.",
    a: "Lolly Daskal",
    c: "92",
    h: "<blockquote>&ldquo;Becoming a great leader doesn't mean being perfect. it means living with your imperfections.&rdquo; &mdash; <footer>Lolly Daskal</footer></blockquote>",
  },
  {
    q: "Be approximately right rather than exactly wrong.",
    a: "John Tukey",
    c: "49",
    h: "<blockquote>&ldquo;Be approximately right rather than exactly wrong.&rdquo; &mdash; <footer>John Tukey</footer></blockquote>",
  },
  {
    q: "Tension is who you think you should be. Relaxation is who you are.",
    a: "Chinese Proverb",
    c: "66",
    h: "<blockquote>&ldquo;Tension is who you think you should be. Relaxation is who you are.&rdquo; &mdash; <footer>Chinese Proverb</footer></blockquote>",
  },
  {
    q: "Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine.",
    a: "Roy T. Bennett",
    c: "118",
    h: "<blockquote>&ldquo;Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine.&rdquo; &mdash; <footer>Roy T. Bennett</footer></blockquote>",
  },
  {
    q: "People don't realize that now is all there ever is; there is no past or future except as memory or anticipation in your mind.",
    a: "Eckhart Tolle",
    c: "125",
    h: "<blockquote>&ldquo;People don't realize that now is all there ever is; there is no past or future except as memory or anticipation in your mind.&rdquo; &mdash; <footer>Eckhart Tolle</footer></blockquote>",
  },
  {
    q: "When you've got nothing, you've got nothing to lose.",
    a: "Bob Dylan",
    c: "52",
    h: "<blockquote>&ldquo;When you've got nothing, you've got nothing to lose.&rdquo; &mdash; <footer>Bob Dylan</footer></blockquote>",
  },
  {
    q: "Words are clothes that thoughts wear",
    a: "Samuel Butler",
    c: "36",
    h: "<blockquote>&ldquo;Words are clothes that thoughts wear&rdquo; &mdash; <footer>Samuel Butler</footer></blockquote>",
  },
  {
    q: "The greatest gift that you can give to others is the gift of unconditional love and acceptance. ",
    a: "Brian Tracy",
    c: "96",
    h: "<blockquote>&ldquo;The greatest gift that you can give to others is the gift of unconditional love and acceptance. &rdquo; &mdash; <footer>Brian Tracy</footer></blockquote>",
  },
  {
    q: "Everyone has the right to make his own decisions, but none has the right to force his decision on others.",
    a: "Ayn Rand",
    c: "105",
    h: "<blockquote>&ldquo;Everyone has the right to make his own decisions, but none has the right to force his decision on others.&rdquo; &mdash; <footer>Ayn Rand</footer></blockquote>",
  },
  {
    q: "Why compare yourself with others? No one in the entire world can do a better job of being you than you.",
    a: "Unknown",
    c: "103",
    h: "<blockquote>&ldquo;Why compare yourself with others? No one in the entire world can do a better job of being you than you.&rdquo; &mdash; <footer>Unknown</footer></blockquote>",
  },
  {
    q: "Lost Time is never found again.",
    a: "Benjamin Franklin",
    c: "31",
    h: "<blockquote>&ldquo;Lost Time is never found again.&rdquo; &mdash; <footer>Benjamin Franklin</footer></blockquote>",
  },
  {
    q: "In youth we run into difficulties. In old age difficulties run into us. ",
    a: "Beverly Sills",
    c: "72",
    h: "<blockquote>&ldquo;In youth we run into difficulties. In old age difficulties run into us. &rdquo; &mdash; <footer>Beverly Sills</footer></blockquote>",
  },
  {
    q: "The unthankful heart discovers no mercies; but the thankful heart will find, in every hour, some heavenly blessings.",
    a: "Henry Ward Beecher",
    c: "116",
    h: "<blockquote>&ldquo;The unthankful heart discovers no mercies; but the thankful heart will find, in every hour, some heavenly blessings.&rdquo; &mdash; <footer>Henry Ward Beecher</footer></blockquote>",
  },
  {
    q: "Some of the greater things in life are unseen; that's why you close your eyes when you kiss, cry, or dream.",
    a: "Unknown",
    c: "107",
    h: "<blockquote>&ldquo;Some of the greater things in life are unseen; that's why you close your eyes when you kiss, cry, or dream.&rdquo; &mdash; <footer>Unknown</footer></blockquote>",
  },
  {
    q: "Don't just sit there. Do something. The answers will follow.",
    a: "Mark Manson",
    c: "60",
    h: "<blockquote>&ldquo;Don't just sit there. Do something. The answers will follow.&rdquo; &mdash; <footer>Mark Manson</footer></blockquote>",
  },
  {
    q: "Character is the result of two things: mental attitude and the way we spend our time.",
    a: "Elbert Hubbard",
    c: "85",
    h: "<blockquote>&ldquo;Character is the result of two things: mental attitude and the way we spend our time.&rdquo; &mdash; <footer>Elbert Hubbard</footer></blockquote>",
  },
  {
    q: "The friend is the man who knows all about you, and still likes you.",
    a: "Elbert Hubbard",
    c: "67",
    h: "<blockquote>&ldquo;The friend is the man who knows all about you, and still likes you.&rdquo; &mdash; <footer>Elbert Hubbard</footer></blockquote>",
  },
  {
    q: "Your mind is infinite, it's your doubts that are limiting.",
    a: "Robert Kiyosaki",
    c: "58",
    h: "<blockquote>&ldquo;Your mind is infinite, it's your doubts that are limiting.&rdquo; &mdash; <footer>Robert Kiyosaki</footer></blockquote>",
  },
  {
    q: "Out of your vulnerabilities will come your strength.",
    a: "Sigmund Freud",
    c: "52",
    h: "<blockquote>&ldquo;Out of your vulnerabilities will come your strength.&rdquo; &mdash; <footer>Sigmund Freud</footer></blockquote>",
  },
  {
    q: "One always begins to forgive a place as soon as it's left behind.",
    a: "Charles Dickens",
    c: "65",
    h: "<blockquote>&ldquo;One always begins to forgive a place as soon as it's left behind.&rdquo; &mdash; <footer>Charles Dickens</footer></blockquote>",
  },
  {
    q: "Even if you persuade me, you won't persuade me.",
    a: "Aristophanes",
    c: "47",
    h: "<blockquote>&ldquo;Even if you persuade me, you won't persuade me.&rdquo; &mdash; <footer>Aristophanes</footer></blockquote>",
  },
  {
    q: "Strategy without tactics is the slowest route to victory. Tactics without strategy is the noise before defeat.",
    a: "Sun Tzu",
    c: "110",
    h: "<blockquote>&ldquo;Strategy without tactics is the slowest route to victory. Tactics without strategy is the noise before defeat.&rdquo; &mdash; <footer>Sun Tzu</footer></blockquote>",
  },
  {
    q: "The older you get, the more you understand how your conscience works.",
    a: "Criss Jami",
    c: "69",
    h: "<blockquote>&ldquo;The older you get, the more you understand how your conscience works.&rdquo; &mdash; <footer>Criss Jami</footer></blockquote>",
  },
  {
    q: "Sometimes success isn't about making the right decision, it's more about making some decision.",
    a: "Robin Sharma",
    c: "94",
    h: "<blockquote>&ldquo;Sometimes success isn't about making the right decision, it's more about making some decision.&rdquo; &mdash; <footer>Robin Sharma</footer></blockquote>",
  },
  {
    q: "The way of success is the way of continuous pursuit of knowledge.",
    a: "Napoleon Hill",
    c: "65",
    h: "<blockquote>&ldquo;The way of success is the way of continuous pursuit of knowledge.&rdquo; &mdash; <footer>Napoleon Hill</footer></blockquote>",
  },
  {
    q: "Failure is the highway to success.",
    a: "Og Mandino",
    c: "34",
    h: "<blockquote>&ldquo;Failure is the highway to success.&rdquo; &mdash; <footer>Og Mandino</footer></blockquote>",
  },
  {
    q: "Nearly every crisis seems to be the worst one, but after it's over, it isn't so bad.",
    a: "Harry S. Truman",
    c: "84",
    h: "<blockquote>&ldquo;Nearly every crisis seems to be the worst one, but after it's over, it isn't so bad.&rdquo; &mdash; <footer>Harry S. Truman</footer></blockquote>",
  },
  {
    q: "All you need is passion. If you have a passion for something, you'll create the talent.",
    a: "Yanni",
    c: "87",
    h: "<blockquote>&ldquo;All you need is passion. If you have a passion for something, you'll create the talent.&rdquo; &mdash; <footer>Yanni</footer></blockquote>",
  },
  {
    q: "Life can be wonderful if you're not afraid of it.",
    a: "Charlie Chaplin",
    c: "49",
    h: "<blockquote>&ldquo;Life can be wonderful if you're not afraid of it.&rdquo; &mdash; <footer>Charlie Chaplin</footer></blockquote>",
  },
  {
    q: "Do not ignore the passion that burns in you. Spend time to discover your gift.",
    a: "Steve Harvey",
    c: "78",
    h: "<blockquote>&ldquo;Do not ignore the passion that burns in you. Spend time to discover your gift.&rdquo; &mdash; <footer>Steve Harvey</footer></blockquote>",
  },
  {
    q: "Greatness lies not in being strong, but in the right use of strength.",
    a: "Henry Ward Beecher",
    c: "69",
    h: "<blockquote>&ldquo;Greatness lies not in being strong, but in the right use of strength.&rdquo; &mdash; <footer>Henry Ward Beecher</footer></blockquote>",
  },
  {
    q: "Motivation gets you going and habit gets you there.  ",
    a: "Zig Ziglar",
    c: "53",
    h: "<blockquote>&ldquo;Motivation gets you going and habit gets you there.  &rdquo; &mdash; <footer>Zig Ziglar</footer></blockquote>",
  },
  {
    q: "Happiness depends on your mindset and attitude.",
    a: "Roy T. Bennett",
    c: "47",
    h: "<blockquote>&ldquo;Happiness depends on your mindset and attitude.&rdquo; &mdash; <footer>Roy T. Bennett</footer></blockquote>",
  },
  {
    q: "The only lost cause is one we give up on before we enter the struggle.",
    a: "Vaclav Havel",
    c: "70",
    h: "<blockquote>&ldquo;The only lost cause is one we give up on before we enter the struggle.&rdquo; &mdash; <footer>Vaclav Havel</footer></blockquote>",
  },
  {
    q: "Stop comparing yourself to others and focus on your own improvement.",
    a: "Lolly Daskal",
    c: "68",
    h: "<blockquote>&ldquo;Stop comparing yourself to others and focus on your own improvement.&rdquo; &mdash; <footer>Lolly Daskal</footer></blockquote>",
  },
  {
    q: "The act of taking the first step is what separates the winners from the losers.",
    a: "Brian Tracy",
    c: "79",
    h: "<blockquote>&ldquo;The act of taking the first step is what separates the winners from the losers.&rdquo; &mdash; <footer>Brian Tracy</footer></blockquote>",
  },
  {
    q: "If you want to be happy, do not dwell in the past, do not worry about the future, focus on living fully in the present.",
    a: "Roy T. Bennett",
    c: "119",
    h: "<blockquote>&ldquo;If you want to be happy, do not dwell in the past, do not worry about the future, focus on living fully in the present.&rdquo; &mdash; <footer>Roy T. Bennett</footer></blockquote>",
  },
  {
    q: "A man who acquires the ability to take full possession of his own mind may take possession of anything else to which he is justly entitled.",
    a: "Andrew Carnegie",
    c: "139",
    h: "<blockquote>&ldquo;A man who acquires the ability to take full possession of his own mind may take possession of anything else to which he is justly entitled.&rdquo; &mdash; <footer>Andrew Carnegie</footer></blockquote>",
  },
  {
    q: "Preoccupied with a single leaf you won't see the tree.",
    a: "Unknown",
    c: "54",
    h: "<blockquote>&ldquo;Preoccupied with a single leaf you won't see the tree.&rdquo; &mdash; <footer>Unknown</footer></blockquote>",
  },
  {
    q: "You can never cross the ocean unless you have the courage to lose sight of the shore.",
    a: "Christopher Columbus",
    c: "85",
    h: "<blockquote>&ldquo;You can never cross the ocean unless you have the courage to lose sight of the shore.&rdquo; &mdash; <footer>Christopher Columbus</footer></blockquote>",
  },
  {
    q: "If you love somebody, let them go, for if they return, they were always yours. If they don't, they never were.",
    a: "Kahlil Gibran",
    c: "110",
    h: "<blockquote>&ldquo;If you love somebody, let them go, for if they return, they were always yours. If they don't, they never were.&rdquo; &mdash; <footer>Kahlil Gibran</footer></blockquote>",
  },
  {
    q: "There's no scarcity of opportunity to make a living at what you love. There is only a scarcity of resolve to make it happen.",
    a: "Wayne Dyer",
    c: "124",
    h: "<blockquote>&ldquo;There's no scarcity of opportunity to make a living at what you love. There is only a scarcity of resolve to make it happen.&rdquo; &mdash; <footer>Wayne Dyer</footer></blockquote>",
  },
  {
    q: "The future belongs to those who believe in the beauty of their dreams.",
    a: "Eleanor Roosevelt",
    c: "70",
    h: "<blockquote>&ldquo;The future belongs to those who believe in the beauty of their dreams.&rdquo; &mdash; <footer>Eleanor Roosevelt</footer></blockquote>",
  },
  {
    q: "Love yourself with the same intensity you would use to pull yourself up if you were hanging off a cliff.",
    a: "Kamal Ravikant",
    c: "104",
    h: "<blockquote>&ldquo;Love yourself with the same intensity you would use to pull yourself up if you were hanging off a cliff.&rdquo; &mdash; <footer>Kamal Ravikant</footer></blockquote>",
  },
  {
    q: "Time doesn't heal emotional pain, you need to learn how to let go.",
    a: "Roy T. Bennett",
    c: "66",
    h: "<blockquote>&ldquo;Time doesn't heal emotional pain, you need to learn how to let go.&rdquo; &mdash; <footer>Roy T. Bennett</footer></blockquote>",
  },
  {
    q: "He who laughs at himself never runs out of things to laugh at.",
    a: "Epictetus",
    c: "62",
    h: "<blockquote>&ldquo;He who laughs at himself never runs out of things to laugh at.&rdquo; &mdash; <footer>Epictetus</footer></blockquote>",
  },
  {
    q: "We are all born ignorant, but one must work hard to remain stupid.",
    a: "Benjamin Franklin",
    c: "66",
    h: "<blockquote>&ldquo;We are all born ignorant, but one must work hard to remain stupid.&rdquo; &mdash; <footer>Benjamin Franklin</footer></blockquote>",
  },
  {
    q: "Blessed is he who expects nothing, for he shall be disappointed.",
    a: "Jonathan Swift",
    c: "64",
    h: "<blockquote>&ldquo;Blessed is he who expects nothing, for he shall be disappointed.&rdquo; &mdash; <footer>Jonathan Swift</footer></blockquote>",
  },
  {
    q: "You must welcome change as the rule but not as your ruler. ",
    a: "Denis Waitley",
    c: "59",
    h: "<blockquote>&ldquo;You must welcome change as the rule but not as your ruler. &rdquo; &mdash; <footer>Denis Waitley</footer></blockquote>",
  },
  {
    q: "You were put on this earth to achieve your greatest self, to live out your purpose, and to do it courageously.",
    a: "Steve Maraboli",
    c: "110",
    h: "<blockquote>&ldquo;You were put on this earth to achieve your greatest self, to live out your purpose, and to do it courageously.&rdquo; &mdash; <footer>Steve Maraboli</footer></blockquote>",
  },
  {
    q: "Some people dream of success, while others wake up and work hard at it.",
    a: "Napoleon Hill",
    c: "71",
    h: "<blockquote>&ldquo;Some people dream of success, while others wake up and work hard at it.&rdquo; &mdash; <footer>Napoleon Hill</footer></blockquote>",
  },
  {
    q: "Don't seek, don't search, don't ask, don't knock, don't demand - relax.",
    a: "Osho",
    c: "71",
    h: "<blockquote>&ldquo;Don't seek, don't search, don't ask, don't knock, don't demand - relax.&rdquo; &mdash; <footer>Osho</footer></blockquote>",
  },
  {
    q: "Believe you can and you will be halfway there.",
    a: "Lolly Daskal",
    c: "46",
    h: "<blockquote>&ldquo;Believe you can and you will be halfway there.&rdquo; &mdash; <footer>Lolly Daskal</footer></blockquote>",
  },
  {
    q: "Everything you look at can become a fairy tale and you can get a story from everything you touch.",
    a: "Hans Christian Andersen",
    c: "97",
    h: "<blockquote>&ldquo;Everything you look at can become a fairy tale and you can get a story from everything you touch.&rdquo; &mdash; <footer>Hans Christian Andersen</footer></blockquote>",
  },
  {
    q: "FEAR has two meanings: 'Forget Everything And Run' or 'Face Everything And Rise.' The choice is yours.",
    a: "Zig Ziglar",
    c: "102",
    h: "<blockquote>&ldquo;FEAR has two meanings: 'Forget Everything And Run' or 'Face Everything And Rise.' The choice is yours.&rdquo; &mdash; <footer>Zig Ziglar</footer></blockquote>",
  },
  {
    q: "Loss is nothing else but change and change is nature's delight.",
    a: "Marcus Aurelius",
    c: "63",
    h: "<blockquote>&ldquo;Loss is nothing else but change and change is nature's delight.&rdquo; &mdash; <footer>Marcus Aurelius</footer></blockquote>",
  },
  {
    q: "The few who do are the envy of the many who only watch.",
    a: "Jim Rohn",
    c: "55",
    h: "<blockquote>&ldquo;The few who do are the envy of the many who only watch.&rdquo; &mdash; <footer>Jim Rohn</footer></blockquote>",
  },
  {
    q: "Not all those who wander are lost.",
    a: "J.R.R. Tolkien",
    c: "34",
    h: "<blockquote>&ldquo;Not all those who wander are lost.&rdquo; &mdash; <footer>J.R.R. Tolkien</footer></blockquote>",
  },
  {
    q: "It does not matter how slowly you go so long as you do not stop.",
    a: "Confucius",
    c: "64",
    h: "<blockquote>&ldquo;It does not matter how slowly you go so long as you do not stop.&rdquo; &mdash; <footer>Confucius</footer></blockquote>",
  },
  {
    q: "Take responsibility of your own happiness, never put it in other people's hands.",
    a: "Roy T. Bennett",
    c: "80",
    h: "<blockquote>&ldquo;Take responsibility of your own happiness, never put it in other people's hands.&rdquo; &mdash; <footer>Roy T. Bennett</footer></blockquote>",
  },
  {
    q: "I've always lived in the moment.",
    a: "Yanni",
    c: "32",
    h: "<blockquote>&ldquo;I've always lived in the moment.&rdquo; &mdash; <footer>Yanni</footer></blockquote>",
  },
  {
    q: "The world is a puzzle; no need to make sense out of it.",
    a: "Socrates",
    c: "55",
    h: "<blockquote>&ldquo;The world is a puzzle; no need to make sense out of it.&rdquo; &mdash; <footer>Socrates</footer></blockquote>",
  },
  {
    q: "Tomorrow is only found in the calendar of fools.",
    a: "Og Mandino",
    c: "48",
    h: "<blockquote>&ldquo;Tomorrow is only found in the calendar of fools.&rdquo; &mdash; <footer>Og Mandino</footer></blockquote>",
  },
  {
    q: "Confidence is contagious. So is lack of confidence.",
    a: "Vince Lombardi",
    c: "51",
    h: "<blockquote>&ldquo;Confidence is contagious. So is lack of confidence.&rdquo; &mdash; <footer>Vince Lombardi</footer></blockquote>",
  },
  {
    q: "Our virtues and our failings are inseparable, like force and matter. When they separate, man is no more. ",
    a: "Nikola Tesla",
    c: "105",
    h: "<blockquote>&ldquo;Our virtues and our failings are inseparable, like force and matter. When they separate, man is no more. &rdquo; &mdash; <footer>Nikola Tesla</footer></blockquote>",
  },
  {
    q: "Conflict cannot survive without your participation. ",
    a: "Wayne Dyer",
    c: "52",
    h: "<blockquote>&ldquo;Conflict cannot survive without your participation. &rdquo; &mdash; <footer>Wayne Dyer</footer></blockquote>",
  },
  {
    q: "An ounce of performance is worth pounds of promises.",
    a: "Mae West",
    c: "52",
    h: "<blockquote>&ldquo;An ounce of performance is worth pounds of promises.&rdquo; &mdash; <footer>Mae West</footer></blockquote>",
  },
  {
    q: "We take care of the future best by taking care of the present now.",
    a: "Jon Kabat-Zinn",
    c: "66",
    h: "<blockquote>&ldquo;We take care of the future best by taking care of the present now.&rdquo; &mdash; <footer>Jon Kabat-Zinn</footer></blockquote>",
  },
  {
    q: "He is not a lover who does not love forever.",
    a: "Euripides",
    c: "44",
    h: "<blockquote>&ldquo;He is not a lover who does not love forever.&rdquo; &mdash; <footer>Euripides</footer></blockquote>",
  },
  {
    q: "Money poisons you when you've got it, and starves you when you haven't.",
    a: "D. H. Lawrence",
    c: "71",
    h: "<blockquote>&ldquo;Money poisons you when you've got it, and starves you when you haven't.&rdquo; &mdash; <footer>D. H. Lawrence</footer></blockquote>",
  },
  {
    q: "When you change what you believe, you change what you do.",
    a: "Spencer Johnson",
    c: "57",
    h: "<blockquote>&ldquo;When you change what you believe, you change what you do.&rdquo; &mdash; <footer>Spencer Johnson</footer></blockquote>",
  },
  {
    q: "The only difference between success and failure is the ability to take action.",
    a: "Alexander Graham Bell",
    c: "78",
    h: "<blockquote>&ldquo;The only difference between success and failure is the ability to take action.&rdquo; &mdash; <footer>Alexander Graham Bell</footer></blockquote>",
  },
  {
    q: "Just because something isn't a lie does not mean that it isn't deceptive.",
    a: "Criss Jami",
    c: "73",
    h: "<blockquote>&ldquo;Just because something isn't a lie does not mean that it isn't deceptive.&rdquo; &mdash; <footer>Criss Jami</footer></blockquote>",
  },
  {
    q: "If you're not making mistakes, then you're not doing anything.",
    a: "John Wooden",
    c: "62",
    h: "<blockquote>&ldquo;If you're not making mistakes, then you're not doing anything.&rdquo; &mdash; <footer>John Wooden</footer></blockquote>",
  },
  {
    q: "Until you make the unconscious conscious, it will direct your life and you will call it fate.",
    a: "Carl Jung",
    c: "93",
    h: "<blockquote>&ldquo;Until you make the unconscious conscious, it will direct your life and you will call it fate.&rdquo; &mdash; <footer>Carl Jung</footer></blockquote>",
  },
  {
    q: "If you do what you've always done, you'll get what you've always gotten.",
    a: "Tony Robbins",
    c: "72",
    h: "<blockquote>&ldquo;If you do what you've always done, you'll get what you've always gotten.&rdquo; &mdash; <footer>Tony Robbins</footer></blockquote>",
  },
  {
    q: "Stand up to your obstacles and do something about them. You'll find they haven't half the strength you think they have.",
    a: "Norman Vincent Peale",
    c: "119",
    h: "<blockquote>&ldquo;Stand up to your obstacles and do something about them. You'll find they haven't half the strength you think they have.&rdquo; &mdash; <footer>Norman Vincent Peale</footer></blockquote>",
  },
  {
    q: "The man who asks a question is a fool for a minute, the man who does not ask is a fool for life.",
    a: "Confucius",
    c: "96",
    h: "<blockquote>&ldquo;The man who asks a question is a fool for a minute, the man who does not ask is a fool for life.&rdquo; &mdash; <footer>Confucius</footer></blockquote>",
  },
  {
    q: "Teachers open the door. You enter by yourself. ",
    a: "Chinese Proverb",
    c: "47",
    h: "<blockquote>&ldquo;Teachers open the door. You enter by yourself. &rdquo; &mdash; <footer>Chinese Proverb</footer></blockquote>",
  },
  {
    q: "By failing to prepare, you are preparing to fail.",
    a: "Benjamin Franklin",
    c: "49",
    h: "<blockquote>&ldquo;By failing to prepare, you are preparing to fail.&rdquo; &mdash; <footer>Benjamin Franklin</footer></blockquote>",
  },
  {
    q: "Live as if you were to die tomorrow. Learn as if you were to live forever.",
    a: "Mahatma Gandhi",
    c: "74",
    h: "<blockquote>&ldquo;Live as if you were to die tomorrow. Learn as if you were to live forever.&rdquo; &mdash; <footer>Mahatma Gandhi</footer></blockquote>",
  },
  {
    q: "I know not all that may be coming, but be it what it will, I'll go to it laughing.",
    a: "Herman Melville",
    c: "82",
    h: "<blockquote>&ldquo;I know not all that may be coming, but be it what it will, I'll go to it laughing.&rdquo; &mdash; <footer>Herman Melville</footer></blockquote>",
  },
  {
    q: "Anger is an acid that can do more harm to the vessel in which it is stored than to anything on which it is poured.",
    a: "Mark Twain",
    c: "114",
    h: "<blockquote>&ldquo;Anger is an acid that can do more harm to the vessel in which it is stored than to anything on which it is poured.&rdquo; &mdash; <footer>Mark Twain</footer></blockquote>",
  },
  {
    q: "We will outstretch the hand if you unclench your fist.",
    a: "Barack Obama",
    c: "54",
    h: "<blockquote>&ldquo;We will outstretch the hand if you unclench your fist.&rdquo; &mdash; <footer>Barack Obama</footer></blockquote>",
  },
  {
    q: "If you find you are not valued and appreciated, then shift your attention to places where you will be valued and appreciated.",
    a: "Celestine Chua",
    c: "125",
    h: "<blockquote>&ldquo;If you find you are not valued and appreciated, then shift your attention to places where you will be valued and appreciated.&rdquo; &mdash; <footer>Celestine Chua</footer></blockquote>",
  },
  {
    q: "Fear is your worst enemy. Risk is your best friend.",
    a: "Gurbaksh Chahal",
    c: "51",
    h: "<blockquote>&ldquo;Fear is your worst enemy. Risk is your best friend.&rdquo; &mdash; <footer>Gurbaksh Chahal</footer></blockquote>",
  },
  {
    q: "One must be deeply aware of the impermanence of the world.",
    a: "Dogen",
    c: "58",
    h: "<blockquote>&ldquo;One must be deeply aware of the impermanence of the world.&rdquo; &mdash; <footer>Dogen</footer></blockquote>",
  },
  {
    q: "Learn to sit back and observe, not everything needs a reaction.",
    a: "Unknown",
    c: "63",
    h: "<blockquote>&ldquo;Learn to sit back and observe, not everything needs a reaction.&rdquo; &mdash; <footer>Unknown</footer></blockquote>",
  },
  {
    q: "A good character is the best tombstone. Carve your name on hearts, not on marble.",
    a: "Charles Spurgeon",
    c: "81",
    h: "<blockquote>&ldquo;A good character is the best tombstone. Carve your name on hearts, not on marble.&rdquo; &mdash; <footer>Charles Spurgeon</footer></blockquote>",
  },
  {
    q: "The road to success is always under construction.",
    a: "Steve Harvey",
    c: "49",
    h: "<blockquote>&ldquo;The road to success is always under construction.&rdquo; &mdash; <footer>Steve Harvey</footer></blockquote>",
  },
  {
    q: "To judge a man by his weakest link or deed is like judging the power of the ocean by one wave.",
    a: "Elvis Presley",
    c: "94",
    h: "<blockquote>&ldquo;To judge a man by his weakest link or deed is like judging the power of the ocean by one wave.&rdquo; &mdash; <footer>Elvis Presley</footer></blockquote>",
  },
  {
    q: "Persistence is very important. You should not give up unless you are forced to give up.",
    a: "Elon Musk",
    c: "87",
    h: "<blockquote>&ldquo;Persistence is very important. You should not give up unless you are forced to give up.&rdquo; &mdash; <footer>Elon Musk</footer></blockquote>",
  },
  {
    q: "Trying to predict the future is like trying to drive down a country road at night with no lights while looking out the back window.",
    a: "Peter Drucker",
    c: "131",
    h: "<blockquote>&ldquo;Trying to predict the future is like trying to drive down a country road at night with no lights while looking out the back window.&rdquo; &mdash; <footer>Peter Drucker</footer></blockquote>",
  },
  {
    q: "Remember, hope is a good thing, maybe the best of things.",
    a: "Stephen King",
    c: "57",
    h: "<blockquote>&ldquo;Remember, hope is a good thing, maybe the best of things.&rdquo; &mdash; <footer>Stephen King</footer></blockquote>",
  },
  {
    q: "Everything you look at can become a fairy tale and you can get a story from everything you touch.",
    a: "Hans Christian Andersen",
    c: "97",
    h: "<blockquote>&ldquo;Everything you look at can become a fairy tale and you can get a story from everything you touch.&rdquo; &mdash; <footer>Hans Christian Andersen</footer></blockquote>",
  },
  {
    q: "Man is made by his belief. As he believes, so he is.",
    a: "Bhagavad Gita",
    c: "52",
    h: "<blockquote>&ldquo;Man is made by his belief. As he believes, so he is.&rdquo; &mdash; <footer>Bhagavad Gita</footer></blockquote>",
  },
  {
    q: "Nothing can bring you peace but yourself.",
    a: "Dale Carnegie",
    c: "41",
    h: "<blockquote>&ldquo;Nothing can bring you peace but yourself.&rdquo; &mdash; <footer>Dale Carnegie</footer></blockquote>",
  },
  {
    q: "Remembering that you are going to die is the best way I know to avoid the trap of thinking you have something to lose.",
    a: "Steve Jobs",
    c: "118",
    h: "<blockquote>&ldquo;Remembering that you are going to die is the best way I know to avoid the trap of thinking you have something to lose.&rdquo; &mdash; <footer>Steve Jobs</footer></blockquote>",
  },
  {
    q: "Forever is composed of now's.",
    a: "Emily Dickinson",
    c: "29",
    h: "<blockquote>&ldquo;Forever is composed of now's.&rdquo; &mdash; <footer>Emily Dickinson</footer></blockquote>",
  },
  {
    q: "The attempt to escape from pain, is what creates more pain.",
    a: "Gabor Mate",
    c: "59",
    h: "<blockquote>&ldquo;The attempt to escape from pain, is what creates more pain.&rdquo; &mdash; <footer>Gabor Mate</footer></blockquote>",
  },
  {
    q: "Knowledge has to be improved, challenged, and increased constantly, or it vanishes.",
    a: "Peter Drucker",
    c: "83",
    h: "<blockquote>&ldquo;Knowledge has to be improved, challenged, and increased constantly, or it vanishes.&rdquo; &mdash; <footer>Peter Drucker</footer></blockquote>",
  },
  {
    q: "Dreams are for dreamers. Goals are for achievers.",
    a: "Arnold Schwarzenegger",
    c: "49",
    h: "<blockquote>&ldquo;Dreams are for dreamers. Goals are for achievers.&rdquo; &mdash; <footer>Arnold Schwarzenegger</footer></blockquote>",
  },
  {
    q: "I begin with an idea and then it becomes something else.",
    a: "Pablo Picasso",
    c: "56",
    h: "<blockquote>&ldquo;I begin with an idea and then it becomes something else.&rdquo; &mdash; <footer>Pablo Picasso</footer></blockquote>",
  },
  {
    q: "Teachers open the door. You enter by yourself. ",
    a: "Chinese Proverb",
    c: "47",
    h: "<blockquote>&ldquo;Teachers open the door. You enter by yourself. &rdquo; &mdash; <footer>Chinese Proverb</footer></blockquote>",
  },
  {
    q: "Life comes at us in waves. We can't predict or control those waves, but we can learn to surf.",
    a: "Dan Millman",
    c: "93",
    h: "<blockquote>&ldquo;Life comes at us in waves. We can't predict or control those waves, but we can learn to surf.&rdquo; &mdash; <footer>Dan Millman</footer></blockquote>",
  },
  {
    q: "If you're really truthful with yourself, it's a wonderful guidance.  ",
    a: "Charlie Chaplin",
    c: "69",
    h: "<blockquote>&ldquo;If you're really truthful with yourself, it's a wonderful guidance.  &rdquo; &mdash; <footer>Charlie Chaplin</footer></blockquote>",
  },
  {
    q: "We can change our lives. We can do, have, and be exactly what we wish.",
    a: "Tony Robbins",
    c: "70",
    h: "<blockquote>&ldquo;We can change our lives. We can do, have, and be exactly what we wish.&rdquo; &mdash; <footer>Tony Robbins</footer></blockquote>",
  },
  {
    q: "It is during our darkest moments that we must focus to see the light.",
    a: "Aristotle",
    c: "69",
    h: "<blockquote>&ldquo;It is during our darkest moments that we must focus to see the light.&rdquo; &mdash; <footer>Aristotle</footer></blockquote>",
  },
  {
    q: "You find peace not by rearranging the circumstances of your life, but by realizing who you are at the deepest level.",
    a: "Eckhart Tolle",
    c: "116",
    h: "<blockquote>&ldquo;You find peace not by rearranging the circumstances of your life, but by realizing who you are at the deepest level.&rdquo; &mdash; <footer>Eckhart Tolle</footer></blockquote>",
  },
  {
    q: "All has not been said and never will be.",
    a: "Samuel Beckett",
    c: "40",
    h: "<blockquote>&ldquo;All has not been said and never will be.&rdquo; &mdash; <footer>Samuel Beckett</footer></blockquote>",
  },
  {
    q: "Rest in reason; move in passion.",
    a: "Kahlil Gibran",
    c: "32",
    h: "<blockquote>&ldquo;Rest in reason; move in passion.&rdquo; &mdash; <footer>Kahlil Gibran</footer></blockquote>",
  },
  {
    q: "People tend to complicate their own lives, as if living weren't already complicated enough.",
    a: "Carlos Ruiz Zafon",
    c: "91",
    h: "<blockquote>&ldquo;People tend to complicate their own lives, as if living weren't already complicated enough.&rdquo; &mdash; <footer>Carlos Ruiz Zafon</footer></blockquote>",
  },
  {
    q: "To lose your temper is only useful once a year.",
    a: "Colin R. Davis",
    c: "47",
    h: "<blockquote>&ldquo;To lose your temper is only useful once a year.&rdquo; &mdash; <footer>Colin R. Davis</footer></blockquote>",
  },
  {
    q: "We love the things we love for what they are.",
    a: "Robert Frost",
    c: "45",
    h: "<blockquote>&ldquo;We love the things we love for what they are.&rdquo; &mdash; <footer>Robert Frost</footer></blockquote>",
  },
  {
    q: "Working hard for something we don't care about is called stress: Working hard for something we love is called passion.",
    a: "Simon Sinek",
    c: "118",
    h: "<blockquote>&ldquo;Working hard for something we don't care about is called stress: Working hard for something we love is called passion.&rdquo; &mdash; <footer>Simon Sinek</footer></blockquote>",
  },
  {
    q: "He who cheats the earth will be cheated by the earth.",
    a: "Chinese Proverb",
    c: "53",
    h: "<blockquote>&ldquo;He who cheats the earth will be cheated by the earth.&rdquo; &mdash; <footer>Chinese Proverb</footer></blockquote>",
  },
  {
    q: "If you want to achieve greatness stop asking for permission.",
    a: "Unknown",
    c: "60",
    h: "<blockquote>&ldquo;If you want to achieve greatness stop asking for permission.&rdquo; &mdash; <footer>Unknown</footer></blockquote>",
  },
  {
    q: "I would rather be hated for who I am than loved for who I'm not.  ",
    a: "Wayne Dyer",
    c: "66",
    h: "<blockquote>&ldquo;I would rather be hated for who I am than loved for who I'm not.  &rdquo; &mdash; <footer>Wayne Dyer</footer></blockquote>",
  },
  {
    q: "Reversing your treatment of the man you have wronged is better than asking his forgiveness.",
    a: "Elbert Hubbard",
    c: "91",
    h: "<blockquote>&ldquo;Reversing your treatment of the man you have wronged is better than asking his forgiveness.&rdquo; &mdash; <footer>Elbert Hubbard</footer></blockquote>",
  },
  {
    q: "We have a duty to maintain the light of consciousness to make sure it continues into the future.",
    a: "Elon Musk",
    c: "96",
    h: "<blockquote>&ldquo;We have a duty to maintain the light of consciousness to make sure it continues into the future.&rdquo; &mdash; <footer>Elon Musk</footer></blockquote>",
  },
  {
    q: "What a liberation to realize that 'the voice in my head' is not who I am. Who am I then? The one who sees that.",
    a: "Eckhart Tolle",
    c: "111",
    h: "<blockquote>&ldquo;What a liberation to realize that 'the voice in my head' is not who I am. Who am I then? The one who sees that.&rdquo; &mdash; <footer>Eckhart Tolle</footer></blockquote>",
  },
  {
    q: "The best way to not feel hopeless is to get up and do something.",
    a: "Barack Obama",
    c: "64",
    h: "<blockquote>&ldquo;The best way to not feel hopeless is to get up and do something.&rdquo; &mdash; <footer>Barack Obama</footer></blockquote>",
  },
  {
    q: "Care about what other people think and you will always be their prisoner.",
    a: "Lao Tzu",
    c: "73",
    h: "<blockquote>&ldquo;Care about what other people think and you will always be their prisoner.&rdquo; &mdash; <footer>Lao Tzu</footer></blockquote>",
  },
  {
    q: "Never whine, never complain, never try to justify yourself.",
    a: "Robert Greene",
    c: "59",
    h: "<blockquote>&ldquo;Never whine, never complain, never try to justify yourself.&rdquo; &mdash; <footer>Robert Greene</footer></blockquote>",
  },
  {
    q: "If you do what you've always done, you'll get what you've always gotten.",
    a: "Tony Robbins",
    c: "72",
    h: "<blockquote>&ldquo;If you do what you've always done, you'll get what you've always gotten.&rdquo; &mdash; <footer>Tony Robbins</footer></blockquote>",
  },
  {
    q: "Values are like fingerprints. Nobody's are the same, but you leave 'em all over everything you do.",
    a: "Elvis Presley",
    c: "98",
    h: "<blockquote>&ldquo;Values are like fingerprints. Nobody's are the same, but you leave 'em all over everything you do.&rdquo; &mdash; <footer>Elvis Presley</footer></blockquote>",
  },
  {
    q: "Re-examine all that you have been told... dismiss that which insults your soul.",
    a: "Walt Whitman",
    c: "79",
    h: "<blockquote>&ldquo;Re-examine all that you have been told... dismiss that which insults your soul.&rdquo; &mdash; <footer>Walt Whitman</footer></blockquote>",
  },
  {
    q: "The most important things are the hardest to say.",
    a: "Stephen King",
    c: "49",
    h: "<blockquote>&ldquo;The most important things are the hardest to say.&rdquo; &mdash; <footer>Stephen King</footer></blockquote>",
  },
  {
    q: "Knowing others is wisdom, knowing yourself is enlightenment.",
    a: "Lao Tzu",
    c: "60",
    h: "<blockquote>&ldquo;Knowing others is wisdom, knowing yourself is enlightenment.&rdquo; &mdash; <footer>Lao Tzu</footer></blockquote>",
  },
  {
    q: "Discipline yourself, and others won't need to.",
    a: "John Wooden",
    c: "46",
    h: "<blockquote>&ldquo;Discipline yourself, and others won't need to.&rdquo; &mdash; <footer>John Wooden</footer></blockquote>",
  },
  {
    q: "All life is an experiment. The more experiments you make, the better.",
    a: "Ralph Waldo Emerson",
    c: "69",
    h: "<blockquote>&ldquo;All life is an experiment. The more experiments you make, the better.&rdquo; &mdash; <footer>Ralph Waldo Emerson</footer></blockquote>",
  },
  {
    q: "It's your life; you don't need someone's permission to live the life you want. Be brave to live from your heart.",
    a: "Roy T. Bennett",
    c: "112",
    h: "<blockquote>&ldquo;It's your life; you don't need someone's permission to live the life you want. Be brave to live from your heart.&rdquo; &mdash; <footer>Roy T. Bennett</footer></blockquote>",
  },
  {
    q: "When you rise in the morning, form a resolution to make the day a happy one for a fellow creature.",
    a: "Sydney Smith",
    c: "98",
    h: "<blockquote>&ldquo;When you rise in the morning, form a resolution to make the day a happy one for a fellow creature.&rdquo; &mdash; <footer>Sydney Smith</footer></blockquote>",
  },
  {
    q: "He who knows, does not speak. He who speaks, does not know.",
    a: "Lao Tzu",
    c: "59",
    h: "<blockquote>&ldquo;He who knows, does not speak. He who speaks, does not know.&rdquo; &mdash; <footer>Lao Tzu</footer></blockquote>",
  },
  {
    q: "Fear of death is fear of the Unknown.",
    a: "Adi Da Samraj",
    c: "37",
    h: "<blockquote>&ldquo;Fear of death is fear of the Unknown.&rdquo; &mdash; <footer>Adi Da Samraj</footer></blockquote>",
  },
  {
    q: "Great acts are made up of small deeds.",
    a: "Lao Tzu",
    c: "38",
    h: "<blockquote>&ldquo;Great acts are made up of small deeds.&rdquo; &mdash; <footer>Lao Tzu</footer></blockquote>",
  },
  {
    q: "Anything you may hold firmly in your imagination can be yours.",
    a: "William James",
    c: "62",
    h: "<blockquote>&ldquo;Anything you may hold firmly in your imagination can be yours.&rdquo; &mdash; <footer>William James</footer></blockquote>",
  },
  {
    q: "The heart wants what it wants. There's no logic. ",
    a: "Woody Allen",
    c: "49",
    h: "<blockquote>&ldquo;The heart wants what it wants. There's no logic. &rdquo; &mdash; <footer>Woody Allen</footer></blockquote>",
  },
  {
    q: "It is in the darkness that one finds the light.",
    a: "Meister Eckhart",
    c: "47",
    h: "<blockquote>&ldquo;It is in the darkness that one finds the light.&rdquo; &mdash; <footer>Meister Eckhart</footer></blockquote>",
  },
  {
    q: "Do not bite at the bait of pleasure, till you know there is no hook beneath it.",
    a: "Thomas Jefferson",
    c: "79",
    h: "<blockquote>&ldquo;Do not bite at the bait of pleasure, till you know there is no hook beneath it.&rdquo; &mdash; <footer>Thomas Jefferson</footer></blockquote>",
  },
  {
    q: "Do not regret the past. Look to the future.",
    a: "Soyen Shaku",
    c: "43",
    h: "<blockquote>&ldquo;Do not regret the past. Look to the future.&rdquo; &mdash; <footer>Soyen Shaku</footer></blockquote>",
  },
  {
    q: "A good master leads you to the true master within. Only that master, who is your own higher self, can adequately answer all questions.",
    a: "Ming-Dao Deng",
    c: "134",
    h: "<blockquote>&ldquo;A good master leads you to the true master within. Only that master, who is your own higher self, can adequately answer all questions.&rdquo; &mdash; <footer>Ming-Dao Deng</footer></blockquote>",
  },
  {
    q: "Don't think money does everything or you are going to end up doing everything for money.",
    a: "Voltaire",
    c: "88",
    h: "<blockquote>&ldquo;Don't think money does everything or you are going to end up doing everything for money.&rdquo; &mdash; <footer>Voltaire</footer></blockquote>",
  },
  {
    q: "A dream you dream alone is only a dream. A dream you dream together is reality.",
    a: "Yoko Ono",
    c: "79",
    h: "<blockquote>&ldquo;A dream you dream alone is only a dream. A dream you dream together is reality.&rdquo; &mdash; <footer>Yoko Ono</footer></blockquote>",
  },
  {
    q: "To be happy we need something to solve. Happiness is therefore a form of action.",
    a: "Mark Manson",
    c: "80",
    h: "<blockquote>&ldquo;To be happy we need something to solve. Happiness is therefore a form of action.&rdquo; &mdash; <footer>Mark Manson</footer></blockquote>",
  },
  {
    q: "If you go out looking for friends, you're going to find they are very scarce. If you go out to be a friend, you'll find them everywhere.",
    a: "Zig Ziglar",
    c: "136",
    h: "<blockquote>&ldquo;If you go out looking for friends, you're going to find they are very scarce. If you go out to be a friend, you'll find them everywhere.&rdquo; &mdash; <footer>Zig Ziglar</footer></blockquote>",
  },
  {
    q: "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.",
    a: "Dale Carnegie",
    c: "107",
    h: "<blockquote>&ldquo;Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.&rdquo; &mdash; <footer>Dale Carnegie</footer></blockquote>",
  },
  {
    q: "No matter how qualified or deserving we are, we will never reach a better life until we can imagine it for ourselves and allow ourselves to have it.",
    a: "Richard Bach",
    c: "148",
    h: "<blockquote>&ldquo;No matter how qualified or deserving we are, we will never reach a better life until we can imagine it for ourselves and allow ourselves to have it.&rdquo; &mdash; <footer>Richard Bach</footer></blockquote>",
  },
  {
    q: "A good teacher opens the door for you, but you must enter the room by yourself.",
    a: "Zen Proverb",
    c: "79",
    h: "<blockquote>&ldquo;A good teacher opens the door for you, but you must enter the room by yourself.&rdquo; &mdash; <footer>Zen Proverb</footer></blockquote>",
  },
  {
    q: "It's possible in ways both large or small to make a difference in someone's life.",
    a: "Yanni",
    c: "81",
    h: "<blockquote>&ldquo;It's possible in ways both large or small to make a difference in someone's life.&rdquo; &mdash; <footer>Yanni</footer></blockquote>",
  },
  {
    q: "Men do not attract which they want but that which they are.",
    a: "James Allen",
    c: "59",
    h: "<blockquote>&ldquo;Men do not attract which they want but that which they are.&rdquo; &mdash; <footer>James Allen</footer></blockquote>",
  },
  {
    q: "Turn your face to the sun, as flowers know how to do.",
    a: "Ming-Dao Deng",
    c: "53",
    h: "<blockquote>&ldquo;Turn your face to the sun, as flowers know how to do.&rdquo; &mdash; <footer>Ming-Dao Deng</footer></blockquote>",
  },
  {
    q: "Excuses are the lies you convince yourself are true to avoid proving you are worthy of the gift you were given.",
    a: "Steve Harvey",
    c: "111",
    h: "<blockquote>&ldquo;Excuses are the lies you convince yourself are true to avoid proving you are worthy of the gift you were given.&rdquo; &mdash; <footer>Steve Harvey</footer></blockquote>",
  },
  {
    q: "It is the nature of the wise to resist pleasures, but the foolish to be a slave to them.",
    a: "Epictetus",
    c: "88",
    h: "<blockquote>&ldquo;It is the nature of the wise to resist pleasures, but the foolish to be a slave to them.&rdquo; &mdash; <footer>Epictetus</footer></blockquote>",
  },
  {
    q: "Don't waste your time in anger, regrets, worries, and grudges. Life is too short to be unhappy.",
    a: "Roy T. Bennett",
    c: "95",
    h: "<blockquote>&ldquo;Don't waste your time in anger, regrets, worries, and grudges. Life is too short to be unhappy.&rdquo; &mdash; <footer>Roy T. Bennett</footer></blockquote>",
  },
  {
    q: "Leadership is solving problems",
    a: "Colin Powell",
    c: "30",
    h: "<blockquote>&ldquo;Leadership is solving problems&rdquo; &mdash; <footer>Colin Powell</footer></blockquote>",
  },
  {
    q: "The fact of the matter is that there will be nothing learned from any challenge in which we don't try our hardest.",
    a: "Josh Waitzkin",
    c: "114",
    h: "<blockquote>&ldquo;The fact of the matter is that there will be nothing learned from any challenge in which we don't try our hardest.&rdquo; &mdash; <footer>Josh Waitzkin</footer></blockquote>",
  },
  {
    q: "No matter what happens, always be yourself.",
    a: "Dale Carnegie",
    c: "43",
    h: "<blockquote>&ldquo;No matter what happens, always be yourself.&rdquo; &mdash; <footer>Dale Carnegie</footer></blockquote>",
  },
  {
    q: "We have more possibilities available in each moment than we realize.",
    a: "Thich Nhat Hanh",
    c: "68",
    h: "<blockquote>&ldquo;We have more possibilities available in each moment than we realize.&rdquo; &mdash; <footer>Thich Nhat Hanh</footer></blockquote>",
  },
  {
    q: "Victory is always possible for the person who refuses to stop fighting.",
    a: "Napoleon Hill",
    c: "71",
    h: "<blockquote>&ldquo;Victory is always possible for the person who refuses to stop fighting.&rdquo; &mdash; <footer>Napoleon Hill</footer></blockquote>",
  },
  {
    q: "Never allow a person to tell you no who doesn't have the power to say yes.",
    a: "Eleanor Roosevelt",
    c: "74",
    h: "<blockquote>&ldquo;Never allow a person to tell you no who doesn't have the power to say yes.&rdquo; &mdash; <footer>Eleanor Roosevelt</footer></blockquote>",
  },
  {
    q: "You become a worrier by practicing worry. You become free of worry by practicing the opposite.",
    a: "Norman Vincent Peale",
    c: "94",
    h: "<blockquote>&ldquo;You become a worrier by practicing worry. You become free of worry by practicing the opposite.&rdquo; &mdash; <footer>Norman Vincent Peale</footer></blockquote>",
  },
  {
    q: "All human beings can alter their lives by altering their attitudes.",
    a: "Andrew Carnegie",
    c: "67",
    h: "<blockquote>&ldquo;All human beings can alter their lives by altering their attitudes.&rdquo; &mdash; <footer>Andrew Carnegie</footer></blockquote>",
  },
  {
    q: "True prayer has no set form.",
    a: "Morihei Ueshiba",
    c: "28",
    h: "<blockquote>&ldquo;True prayer has no set form.&rdquo; &mdash; <footer>Morihei Ueshiba</footer></blockquote>",
  },
  {
    q: "I would rather die on my feet than live on my knees.",
    a: "Euripides",
    c: "52",
    h: "<blockquote>&ldquo;I would rather die on my feet than live on my knees.&rdquo; &mdash; <footer>Euripides</footer></blockquote>",
  },
  {
    q: "The older you get, the more you understand how your conscience works.",
    a: "Criss Jami",
    c: "69",
    h: "<blockquote>&ldquo;The older you get, the more you understand how your conscience works.&rdquo; &mdash; <footer>Criss Jami</footer></blockquote>",
  },
  {
    q: "Would you rather learn to deal with the truth now than be forced to do so later on?",
    a: "Celestine Chua",
    c: "83",
    h: "<blockquote>&ldquo;Would you rather learn to deal with the truth now than be forced to do so later on?&rdquo; &mdash; <footer>Celestine Chua</footer></blockquote>",
  },
  {
    q: "When you change what you believe, you change what you do.",
    a: "Spencer Johnson",
    c: "57",
    h: "<blockquote>&ldquo;When you change what you believe, you change what you do.&rdquo; &mdash; <footer>Spencer Johnson</footer></blockquote>",
  },
  {
    q: "It isn't that they can't see the solution. It is that they can't see the problem.",
    a: "Gilbert Chesterton",
    c: "81",
    h: "<blockquote>&ldquo;It isn't that they can't see the solution. It is that they can't see the problem.&rdquo; &mdash; <footer>Gilbert Chesterton</footer></blockquote>",
  },
  {
    q: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
    a: "Buddha",
    c: "97",
    h: "<blockquote>&ldquo;Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.&rdquo; &mdash; <footer>Buddha</footer></blockquote>",
  },
  {
    q: "Everyday you can take a tiny step in the right direction.",
    a: "Unknown",
    c: "57",
    h: "<blockquote>&ldquo;Everyday you can take a tiny step in the right direction.&rdquo; &mdash; <footer>Unknown</footer></blockquote>",
  },
  {
    q: "I alone cannot change the world, but I can cast a stone across the waters to create many ripples.",
    a: "Mother Teresa",
    c: "97",
    h: "<blockquote>&ldquo;I alone cannot change the world, but I can cast a stone across the waters to create many ripples.&rdquo; &mdash; <footer>Mother Teresa</footer></blockquote>",
  },
  {
    q: "Never put off to tomorrow what you can do to-day.",
    a: "Thomas Jefferson",
    c: "49",
    h: "<blockquote>&ldquo;Never put off to tomorrow what you can do to-day.&rdquo; &mdash; <footer>Thomas Jefferson</footer></blockquote>",
  },
  {
    q: "Success is achieved and maintained by those who try and keep trying. ",
    a: "W. Clement Stone",
    c: "69",
    h: "<blockquote>&ldquo;Success is achieved and maintained by those who try and keep trying. &rdquo; &mdash; <footer>W. Clement Stone</footer></blockquote>",
  },
  {
    q: "If you don't read the newspaper, you're uninformed. If you read the newspaper, you're misinformed.",
    a: "Mark Twain",
    c: "98",
    h: "<blockquote>&ldquo;If you don't read the newspaper, you're uninformed. If you read the newspaper, you're misinformed.&rdquo; &mdash; <footer>Mark Twain</footer></blockquote>",
  },
  {
    q: "In spite of everything, I shall rise again.",
    a: "Vincent van Gogh",
    c: "43",
    h: "<blockquote>&ldquo;In spite of everything, I shall rise again.&rdquo; &mdash; <footer>Vincent van Gogh</footer></blockquote>",
  },
  {
    q: "Every day may not be good, but there's something good in every day.",
    a: "Unknown",
    c: "67",
    h: "<blockquote>&ldquo;Every day may not be good, but there's something good in every day.&rdquo; &mdash; <footer>Unknown</footer></blockquote>",
  },
  {
    q: "Failing is another stepping stone to greatness.",
    a: "Oprah Winfrey",
    c: "47",
    h: "<blockquote>&ldquo;Failing is another stepping stone to greatness.&rdquo; &mdash; <footer>Oprah Winfrey</footer></blockquote>",
  },
  {
    q: "In the end, it's not the years in your life that count. It's the life in your years.",
    a: "Abraham Lincoln",
    c: "84",
    h: "<blockquote>&ldquo;In the end, it's not the years in your life that count. It's the life in your years.&rdquo; &mdash; <footer>Abraham Lincoln</footer></blockquote>",
  },
  {
    q: "To know your Enemy, you must become your Enemy.",
    a: "Sun Tzu",
    c: "47",
    h: "<blockquote>&ldquo;To know your Enemy, you must become your Enemy.&rdquo; &mdash; <footer>Sun Tzu</footer></blockquote>",
  },
  {
    q: "Life comes at us in waves. We can't predict or control those waves, but we can learn to surf.",
    a: "Dan Millman",
    c: "93",
    h: "<blockquote>&ldquo;Life comes at us in waves. We can't predict or control those waves, but we can learn to surf.&rdquo; &mdash; <footer>Dan Millman</footer></blockquote>",
  },
  {
    q: "Singleness of purpose is one of the chief essentials for success in life, no matter what may be one's aim.",
    a: "John D. Rockefeller",
    c: "106",
    h: "<blockquote>&ldquo;Singleness of purpose is one of the chief essentials for success in life, no matter what may be one's aim.&rdquo; &mdash; <footer>John D. Rockefeller</footer></blockquote>",
  },
  {
    q: "It's just a bad day, not a bad life.",
    a: "Mary Engelbreit",
    c: "36",
    h: "<blockquote>&ldquo;It's just a bad day, not a bad life.&rdquo; &mdash; <footer>Mary Engelbreit</footer></blockquote>",
  },
  {
    q: "Winning isn't always championships.",
    a: "Michael Jordan",
    c: "35",
    h: "<blockquote>&ldquo;Winning isn't always championships.&rdquo; &mdash; <footer>Michael Jordan</footer></blockquote>",
  },
  {
    q: "There is nothing quite so tragic as a young cynic.",
    a: "Maya Angelou",
    c: "50",
    h: "<blockquote>&ldquo;There is nothing quite so tragic as a young cynic.&rdquo; &mdash; <footer>Maya Angelou</footer></blockquote>",
  },
  {
    q: "Nothing ever happened in the past that can prevent you from being present now; and if the past cannot prevent you from being present now, what power does it have?",
    a: "Eckhart Tolle",
    c: "162",
    h: "<blockquote>&ldquo;Nothing ever happened in the past that can prevent you from being present now; and if the past cannot prevent you from being present now, what power does it have?&rdquo; &mdash; <footer>Eckhart Tolle</footer></blockquote>",
  },
  {
    q: "The future is no more uncertain than the present.",
    a: "Walt Whitman",
    c: "49",
    h: "<blockquote>&ldquo;The future is no more uncertain than the present.&rdquo; &mdash; <footer>Walt Whitman</footer></blockquote>",
  },
  {
    q: "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    a: "Henry David Thoreau",
    c: "100",
    h: "<blockquote>&ldquo;What you get by achieving your goals is not as important as what you become by achieving your goals.&rdquo; &mdash; <footer>Henry David Thoreau</footer></blockquote>",
  },
  {
    q: "No man is happy who does not think himself so.",
    a: "Norman Vincent Peale",
    c: "46",
    h: "<blockquote>&ldquo;No man is happy who does not think himself so.&rdquo; &mdash; <footer>Norman Vincent Peale</footer></blockquote>",
  },
  {
    q: "It is the power of the mind to be unconquerable.",
    a: "Seneca",
    c: "48",
    h: "<blockquote>&ldquo;It is the power of the mind to be unconquerable.&rdquo; &mdash; <footer>Seneca</footer></blockquote>",
  },
  {
    q: "Character is the result of two things: mental attitude and the way we spend our time.",
    a: "Elbert Hubbard",
    c: "85",
    h: "<blockquote>&ldquo;Character is the result of two things: mental attitude and the way we spend our time.&rdquo; &mdash; <footer>Elbert Hubbard</footer></blockquote>",
  },
  {
    q: "The more you are motivated by Love, The more Fearless & Free your action will be.",
    a: "Dalai Lama",
    c: "81",
    h: "<blockquote>&ldquo;The more you are motivated by Love, The more Fearless & Free your action will be.&rdquo; &mdash; <footer>Dalai Lama</footer></blockquote>",
  },
  {
    q: "There is no way to happiness - happiness is the way.",
    a: "Thich Nhat Hanh",
    c: "52",
    h: "<blockquote>&ldquo;There is no way to happiness - happiness is the way.&rdquo; &mdash; <footer>Thich Nhat Hanh</footer></blockquote>",
  },
  {
    q: "Longevity is a fleeting moment that lasts forever.",
    a: "Vidal Sassoon",
    c: "50",
    h: "<blockquote>&ldquo;Longevity is a fleeting moment that lasts forever.&rdquo; &mdash; <footer>Vidal Sassoon</footer></blockquote>",
  },
  {
    q: "Success is nothing more than a few simple disciplines practiced every day.",
    a: "Jim Rohn",
    c: "74",
    h: "<blockquote>&ldquo;Success is nothing more than a few simple disciplines practiced every day.&rdquo; &mdash; <footer>Jim Rohn</footer></blockquote>",
  },
  {
    q: "What we dwell on is who we become.",
    a: "Oprah Winfrey",
    c: "34",
    h: "<blockquote>&ldquo;What we dwell on is who we become.&rdquo; &mdash; <footer>Oprah Winfrey</footer></blockquote>",
  },
  {
    q: "The more you are focused on time - past and future - the more you miss the Now, the most precious thing there is.",
    a: "Eckhart Tolle",
    c: "113",
    h: "<blockquote>&ldquo;The more you are focused on time - past and future - the more you miss the Now, the most precious thing there is.&rdquo; &mdash; <footer>Eckhart Tolle</footer></blockquote>",
  },
  {
    q: "Never lose hope. Storms make people stronger and never last forever.",
    a: "Roy T. Bennett",
    c: "68",
    h: "<blockquote>&ldquo;Never lose hope. Storms make people stronger and never last forever.&rdquo; &mdash; <footer>Roy T. Bennett</footer></blockquote>",
  },
  {
    q: "Successful people ask better questions, and as a result, they get better answers.",
    a: "Tony Robbins",
    c: "81",
    h: "<blockquote>&ldquo;Successful people ask better questions, and as a result, they get better answers.&rdquo; &mdash; <footer>Tony Robbins</footer></blockquote>",
  },
  {
    q: "The most efficient way of rendering the poor harmless is to teach them to want to imitate the rich.",
    a: "Carlos Ruiz Zafon",
    c: "99",
    h: "<blockquote>&ldquo;The most efficient way of rendering the poor harmless is to teach them to want to imitate the rich.&rdquo; &mdash; <footer>Carlos Ruiz Zafon</footer></blockquote>",
  },
  {
    q: "The scariest monsters are the ones that lurk within our souls.",
    a: "Edgar Allan Poe",
    c: "62",
    h: "<blockquote>&ldquo;The scariest monsters are the ones that lurk within our souls.&rdquo; &mdash; <footer>Edgar Allan Poe</footer></blockquote>",
  },
  {
    q: "Wealth consists not in having great possessions, but in having few wants.",
    a: "Epictetus",
    c: "73",
    h: "<blockquote>&ldquo;Wealth consists not in having great possessions, but in having few wants.&rdquo; &mdash; <footer>Epictetus</footer></blockquote>",
  },
  {
    q: "Walk with those seeking truth... RUN FROM THOSE WHO THINK THEY'VE FOUND IT.",
    a: "Deepak Chopra",
    c: "75",
    h: "<blockquote>&ldquo;Walk with those seeking truth... RUN FROM THOSE WHO THINK THEY'VE FOUND IT.&rdquo; &mdash; <footer>Deepak Chopra</footer></blockquote>",
  },
  {
    q: "Do something to move yourself toward your major goal every day.",
    a: "Brian Tracy",
    c: "63",
    h: "<blockquote>&ldquo;Do something to move yourself toward your major goal every day.&rdquo; &mdash; <footer>Brian Tracy</footer></blockquote>",
  },
  {
    q: "Some of us learn from other people's mistakes and the rest of us have to be other people.  ",
    a: "Zig Ziglar",
    c: "91",
    h: "<blockquote>&ldquo;Some of us learn from other people's mistakes and the rest of us have to be other people.  &rdquo; &mdash; <footer>Zig Ziglar</footer></blockquote>",
  },
  {
    q: "You can never get enough of what you don't need to make you happy.",
    a: "Eric Hoffer",
    c: "66",
    h: "<blockquote>&ldquo;You can never get enough of what you don't need to make you happy.&rdquo; &mdash; <footer>Eric Hoffer</footer></blockquote>",
  },
  {
    q: "In the practice of tolerance, one's enemy is the best teacher.",
    a: "Dalai Lama",
    c: "62",
    h: "<blockquote>&ldquo;In the practice of tolerance, one's enemy is the best teacher.&rdquo; &mdash; <footer>Dalai Lama</footer></blockquote>",
  },
  {
    q: "Nothing is more real than nothing.",
    a: "Samuel Beckett",
    c: "34",
    h: "<blockquote>&ldquo;Nothing is more real than nothing.&rdquo; &mdash; <footer>Samuel Beckett</footer></blockquote>",
  },
  {
    q: "A journey of a thousand miles begins with a single step.",
    a: "Lao Tzu",
    c: "56",
    h: "<blockquote>&ldquo;A journey of a thousand miles begins with a single step.&rdquo; &mdash; <footer>Lao Tzu</footer></blockquote>",
  },
  {
    q: "Animals don't hate, and we're supposed to be better than them.",
    a: "Elvis Presley",
    c: "62",
    h: "<blockquote>&ldquo;Animals don't hate, and we're supposed to be better than them.&rdquo; &mdash; <footer>Elvis Presley</footer></blockquote>",
  },
  {
    q: "It's not what happens to you, but how you react to it that matters.",
    a: "Epictetus",
    c: "67",
    h: "<blockquote>&ldquo;It's not what happens to you, but how you react to it that matters.&rdquo; &mdash; <footer>Epictetus</footer></blockquote>",
  },
  {
    q: "Death walks faster than the wind and never returns what he has taken.",
    a: "Hans Christian Andersen",
    c: "69",
    h: "<blockquote>&ldquo;Death walks faster than the wind and never returns what he has taken.&rdquo; &mdash; <footer>Hans Christian Andersen</footer></blockquote>",
  },
  {
    q: "If you're brave enough to say goodbye, life will reward you with a new hello.",
    a: "Paulo Coelho",
    c: "77",
    h: "<blockquote>&ldquo;If you're brave enough to say goodbye, life will reward you with a new hello.&rdquo; &mdash; <footer>Paulo Coelho</footer></blockquote>",
  },
  {
    q: "The first rule of business; treat others like they want to treat you.",
    a: "Charles Dickens",
    c: "69",
    h: "<blockquote>&ldquo;The first rule of business; treat others like they want to treat you.&rdquo; &mdash; <footer>Charles Dickens</footer></blockquote>",
  },
  {
    q: "Only the hand that erases can write the true thing.",
    a: "Meister Eckhart",
    c: "51",
    h: "<blockquote>&ldquo;Only the hand that erases can write the true thing.&rdquo; &mdash; <footer>Meister Eckhart</footer></blockquote>",
  },
  {
    q: "The worst part of success is trying to find someone who is happy for you.",
    a: "Bette Midler",
    c: "73",
    h: "<blockquote>&ldquo;The worst part of success is trying to find someone who is happy for you.&rdquo; &mdash; <footer>Bette Midler</footer></blockquote>",
  },
  {
    q: "Optimism is the one quality more associated with success and happiness than any other.",
    a: "Brian Tracy",
    c: "86",
    h: "<blockquote>&ldquo;Optimism is the one quality more associated with success and happiness than any other.&rdquo; &mdash; <footer>Brian Tracy</footer></blockquote>",
  },
  {
    q: "You may be disappointed if you fail, but you are doomed if you don't try.",
    a: "Beverly Sills",
    c: "73",
    h: "<blockquote>&ldquo;You may be disappointed if you fail, but you are doomed if you don't try.&rdquo; &mdash; <footer>Beverly Sills</footer></blockquote>",
  },
  {
    q: "Quality means doing it right when no one is looking.",
    a: "Henry Ford",
    c: "52",
    h: "<blockquote>&ldquo;Quality means doing it right when no one is looking.&rdquo; &mdash; <footer>Henry Ford</footer></blockquote>",
  },
  {
    q: "Life is a succession of lessons, which must be lived to be understood.",
    a: "Ralph Waldo Emerson",
    c: "70",
    h: "<blockquote>&ldquo;Life is a succession of lessons, which must be lived to be understood.&rdquo; &mdash; <footer>Ralph Waldo Emerson</footer></blockquote>",
  },
  {
    q: "Question everything. Learn something. Answer nothing.",
    a: "Euripides",
    c: "53",
    h: "<blockquote>&ldquo;Question everything. Learn something. Answer nothing.&rdquo; &mdash; <footer>Euripides</footer></blockquote>",
  },
  {
    q: "Have the courage to follow your heart and intuition. They somehow know what you truly want to become.",
    a: "Steve Jobs",
    c: "101",
    h: "<blockquote>&ldquo;Have the courage to follow your heart and intuition. They somehow know what you truly want to become.&rdquo; &mdash; <footer>Steve Jobs</footer></blockquote>",
  },
  {
    q: "Correct what you can. Learn from what you can't.",
    a: "Toni Morrison",
    c: "48",
    h: "<blockquote>&ldquo;Correct what you can. Learn from what you can't.&rdquo; &mdash; <footer>Toni Morrison</footer></blockquote>",
  },
  {
    q: "Stay away from people who makes you feel like you are wasting their time.",
    a: "Paulo Coelho",
    c: "73",
    h: "<blockquote>&ldquo;Stay away from people who makes you feel like you are wasting their time.&rdquo; &mdash; <footer>Paulo Coelho</footer></blockquote>",
  },
  {
    q: "What would you do if you weren't afraid?",
    a: "Spencer Johnson",
    c: "40",
    h: "<blockquote>&ldquo;What would you do if you weren't afraid?&rdquo; &mdash; <footer>Spencer Johnson</footer></blockquote>",
  },
  {
    q: "Experience is simply the name we give our mistakes. ",
    a: "Oscar Wilde",
    c: "52",
    h: "<blockquote>&ldquo;Experience is simply the name we give our mistakes. &rdquo; &mdash; <footer>Oscar Wilde</footer></blockquote>",
  },
  {
    q: "Walking with a friend in the dark is better than walking alone in the light.",
    a: "Helen Keller",
    c: "76",
    h: "<blockquote>&ldquo;Walking with a friend in the dark is better than walking alone in the light.&rdquo; &mdash; <footer>Helen Keller</footer></blockquote>",
  },
  {
    q: "It is not how much we have, but how much we enjoy, that makes happiness.",
    a: "Charles Spurgeon",
    c: "72",
    h: "<blockquote>&ldquo;It is not how much we have, but how much we enjoy, that makes happiness.&rdquo; &mdash; <footer>Charles Spurgeon</footer></blockquote>",
  },
  {
    q: "Focus is a matter of deciding what things you're not going to do.",
    a: "John Carmack",
    c: "65",
    h: "<blockquote>&ldquo;Focus is a matter of deciding what things you're not going to do.&rdquo; &mdash; <footer>John Carmack</footer></blockquote>",
  },
  {
    q: "The quality of your commitments will determine the course of your life.",
    a: "Ralph Marston",
    c: "71",
    h: "<blockquote>&ldquo;The quality of your commitments will determine the course of your life.&rdquo; &mdash; <footer>Ralph Marston</footer></blockquote>",
  },
  {
    q: "The worst part of success is trying to find someone who is happy for you.",
    a: "Bette Midler",
    c: "73",
    h: "<blockquote>&ldquo;The worst part of success is trying to find someone who is happy for you.&rdquo; &mdash; <footer>Bette Midler</footer></blockquote>",
  },
  {
    q: "To be prepared is half the victory. ",
    a: "Miguel de Cervantes",
    c: "36",
    h: "<blockquote>&ldquo;To be prepared is half the victory. &rdquo; &mdash; <footer>Miguel de Cervantes</footer></blockquote>",
  },
  {
    q: "There can be no deep disappointment where there is not deep love.",
    a: "Martin Luther King, Jr.",
    c: "65",
    h: "<blockquote>&ldquo;There can be no deep disappointment where there is not deep love.&rdquo; &mdash; <footer>Martin Luther King, Jr.</footer></blockquote>",
  },
  {
    q: "Hope is a waking dream.",
    a: "Aristotle",
    c: "23",
    h: "<blockquote>&ldquo;Hope is a waking dream.&rdquo; &mdash; <footer>Aristotle</footer></blockquote>",
  },
  {
    q: "A crisis is an opportunity riding the dangerous wind.",
    a: "Chinese Proverb",
    c: "53",
    h: "<blockquote>&ldquo;A crisis is an opportunity riding the dangerous wind.&rdquo; &mdash; <footer>Chinese Proverb</footer></blockquote>",
  },
  {
    q: "Life has the name of life, but in reality it is death.",
    a: "Heraclitus",
    c: "54",
    h: "<blockquote>&ldquo;Life has the name of life, but in reality it is death.&rdquo; &mdash; <footer>Heraclitus</footer></blockquote>",
  },
  {
    q: "Convinced myself, I seek not to convince.",
    a: "Edgar Allan Poe",
    c: "41",
    h: "<blockquote>&ldquo;Convinced myself, I seek not to convince.&rdquo; &mdash; <footer>Edgar Allan Poe</footer></blockquote>",
  },
  {
    q: "Respect is earned by effort not age, all things age without effort.",
    a: "C. Sean McGee",
    c: "67",
    h: "<blockquote>&ldquo;Respect is earned by effort not age, all things age without effort.&rdquo; &mdash; <footer>C. Sean McGee</footer></blockquote>",
  },
  {
    q: "There are two kinds of perfect people: those who are dead, and those who have not been born yet.",
    a: "Chinese Proverb",
    c: "96",
    h: "<blockquote>&ldquo;There are two kinds of perfect people: those who are dead, and those who have not been born yet.&rdquo; &mdash; <footer>Chinese Proverb</footer></blockquote>",
  },
  {
    q: "While some of us act without thinking, too many of us think without acting.",
    a: "Dan Millman",
    c: "75",
    h: "<blockquote>&ldquo;While some of us act without thinking, too many of us think without acting.&rdquo; &mdash; <footer>Dan Millman</footer></blockquote>",
  },
  {
    q: "Someone who points out your flaws to you is not necessarily your enemy. Someone who speaks of your virtues is not necessarily your friend.",
    a: "Zen Proverb",
    c: "138",
    h: "<blockquote>&ldquo;Someone who points out your flaws to you is not necessarily your enemy. Someone who speaks of your virtues is not necessarily your friend.&rdquo; &mdash; <footer>Zen Proverb</footer></blockquote>",
  },
  {
    q: "We will now discuss in a little more detail the Struggle for Existence.",
    a: "Charles Darwin",
    c: "71",
    h: "<blockquote>&ldquo;We will now discuss in a little more detail the Struggle for Existence.&rdquo; &mdash; <footer>Charles Darwin</footer></blockquote>",
  },
  {
    q: "Your vision will become clear only when you can look into your own heart.",
    a: "Lolly Daskal",
    c: "73",
    h: "<blockquote>&ldquo;Your vision will become clear only when you can look into your own heart.&rdquo; &mdash; <footer>Lolly Daskal</footer></blockquote>",
  },
  {
    q: "It's not the size of the dog in the fight, it's the size of the fight in the dog.",
    a: "Mark Twain",
    c: "81",
    h: "<blockquote>&ldquo;It's not the size of the dog in the fight, it's the size of the fight in the dog.&rdquo; &mdash; <footer>Mark Twain</footer></blockquote>",
  },
  {
    q: "Don't measure yourself by what you have accomplished, but by what you should have accomplished with your ability.",
    a: "John Wooden",
    c: "113",
    h: "<blockquote>&ldquo;Don't measure yourself by what you have accomplished, but by what you should have accomplished with your ability.&rdquo; &mdash; <footer>John Wooden</footer></blockquote>",
  },
  {
    q: "A thing must be loved before it is lovable.",
    a: "Gilbert Chesterton",
    c: "43",
    h: "<blockquote>&ldquo;A thing must be loved before it is lovable.&rdquo; &mdash; <footer>Gilbert Chesterton</footer></blockquote>",
  },
  {
    q: "Nature is pleased with simplicity. And nature is no dummy.",
    a: "Isaac Newton",
    c: "58",
    h: "<blockquote>&ldquo;Nature is pleased with simplicity. And nature is no dummy.&rdquo; &mdash; <footer>Isaac Newton</footer></blockquote>",
  },
  {
    q: "Don't spend major time on minor things.",
    a: "Jim Rohn",
    c: "39",
    h: "<blockquote>&ldquo;Don't spend major time on minor things.&rdquo; &mdash; <footer>Jim Rohn</footer></blockquote>",
  },
  {
    q: "One of the first signs of the beginning of understanding is the wish to die. ",
    a: "Franz Kafka",
    c: "77",
    h: "<blockquote>&ldquo;One of the first signs of the beginning of understanding is the wish to die. &rdquo; &mdash; <footer>Franz Kafka</footer></blockquote>",
  },
  {
    q: "The more something scares you, the more you should do it.",
    a: "Mark Manson",
    c: "57",
    h: "<blockquote>&ldquo;The more something scares you, the more you should do it.&rdquo; &mdash; <footer>Mark Manson</footer></blockquote>",
  },
  {
    q: "It's not how much money you make, it's how much money you keep.",
    a: "Robert Kiyosaki",
    c: "63",
    h: "<blockquote>&ldquo;It's not how much money you make, it's how much money you keep.&rdquo; &mdash; <footer>Robert Kiyosaki</footer></blockquote>",
  },
  {
    q: "Only the educated are free.",
    a: "Epictetus",
    c: "27",
    h: "<blockquote>&ldquo;Only the educated are free.&rdquo; &mdash; <footer>Epictetus</footer></blockquote>",
  },
  {
    q: "The single most powerful asset we all have is our mind.",
    a: "Robert Kiyosaki",
    c: "55",
    h: "<blockquote>&ldquo;The single most powerful asset we all have is our mind.&rdquo; &mdash; <footer>Robert Kiyosaki</footer></blockquote>",
  },
  {
    q: "It's easier to go down a hill than up it but the view is much better at the top.",
    a: "Henry Ward Beecher",
    c: "80",
    h: "<blockquote>&ldquo;It's easier to go down a hill than up it but the view is much better at the top.&rdquo; &mdash; <footer>Henry Ward Beecher</footer></blockquote>",
  },
  {
    q: "Don't set your own goals by what other people make important.",
    a: "Lolly Daskal",
    c: "61",
    h: "<blockquote>&ldquo;Don't set your own goals by what other people make important.&rdquo; &mdash; <footer>Lolly Daskal</footer></blockquote>",
  },
  {
    q: "Most people do not really want freedom, because freedom involves responsibility, and most people are frightened of responsibility.",
    a: "Sigmund Freud",
    c: "130",
    h: "<blockquote>&ldquo;Most people do not really want freedom, because freedom involves responsibility, and most people are frightened of responsibility.&rdquo; &mdash; <footer>Sigmund Freud</footer></blockquote>",
  },
  {
    q: "Circumstances rule men; men do not rule circumstances. ",
    a: "Herodotus",
    c: "55",
    h: "<blockquote>&ldquo;Circumstances rule men; men do not rule circumstances. &rdquo; &mdash; <footer>Herodotus</footer></blockquote>",
  },
  {
    q: "If you put yourself in a position where you have to stretch outside your comfort zone, then you are forced to expand your consciousness.",
    a: "Unknown",
    c: "136",
    h: "<blockquote>&ldquo;If you put yourself in a position where you have to stretch outside your comfort zone, then you are forced to expand your consciousness.&rdquo; &mdash; <footer>Unknown</footer></blockquote>",
  },
  {
    q: "Desire for the fruits of work must never be your motive in working.",
    a: "Bhagavad Gita",
    c: "67",
    h: "<blockquote>&ldquo;Desire for the fruits of work must never be your motive in working.&rdquo; &mdash; <footer>Bhagavad Gita</footer></blockquote>",
  },
  {
    q: "The question isn't who is going to let me; it's who is going to stop me.",
    a: "Ayn Rand",
    c: "72",
    h: "<blockquote>&ldquo;The question isn't who is going to let me; it's who is going to stop me.&rdquo; &mdash; <footer>Ayn Rand</footer></blockquote>",
  },
  {
    q: "Failing is another stepping stone to greatness.",
    a: "Oprah Winfrey",
    c: "47",
    h: "<blockquote>&ldquo;Failing is another stepping stone to greatness.&rdquo; &mdash; <footer>Oprah Winfrey</footer></blockquote>",
  },
  {
    q: "Where you are right now doesn't have to determine where you'll end up.",
    a: "Barack Obama",
    c: "70",
    h: "<blockquote>&ldquo;Where you are right now doesn't have to determine where you'll end up.&rdquo; &mdash; <footer>Barack Obama</footer></blockquote>",
  },
  {
    q: "Happiness is when what you think, what you say, and what you do are in harmony.",
    a: "Mahatma Gandhi",
    c: "79",
    h: "<blockquote>&ldquo;Happiness is when what you think, what you say, and what you do are in harmony.&rdquo; &mdash; <footer>Mahatma Gandhi</footer></blockquote>",
  },
  {
    q: "The greater the impact you want to make, the greater your influence needs to be.",
    a: "Lolly Daskal",
    c: "80",
    h: "<blockquote>&ldquo;The greater the impact you want to make, the greater your influence needs to be.&rdquo; &mdash; <footer>Lolly Daskal</footer></blockquote>",
  },
  {
    q: "It is under the greatest adversity that there exists the greatest potential for doing good, both for oneself and others.",
    a: "Dalai Lama",
    c: "120",
    h: "<blockquote>&ldquo;It is under the greatest adversity that there exists the greatest potential for doing good, both for oneself and others.&rdquo; &mdash; <footer>Dalai Lama</footer></blockquote>",
  },
  {
    q: "You can't wait for inspiration. You have to go after it with a club. ",
    a: "Jack London",
    c: "69",
    h: "<blockquote>&ldquo;You can't wait for inspiration. You have to go after it with a club. &rdquo; &mdash; <footer>Jack London</footer></blockquote>",
  },
  {
    q: "Your spirit is the true shield.",
    a: "Morihei Ueshiba",
    c: "31",
    h: "<blockquote>&ldquo;Your spirit is the true shield.&rdquo; &mdash; <footer>Morihei Ueshiba</footer></blockquote>",
  },
  {
    q: "Success is getting what you want, happiness is wanting what you get.",
    a: "W.P. Kinsella",
    c: "68",
    h: "<blockquote>&ldquo;Success is getting what you want, happiness is wanting what you get.&rdquo; &mdash; <footer>W.P. Kinsella</footer></blockquote>",
  },
  {
    q: "We are all in the gutter, but some of us are looking at the stars. ",
    a: "Oscar Wilde",
    c: "67",
    h: "<blockquote>&ldquo;We are all in the gutter, but some of us are looking at the stars. &rdquo; &mdash; <footer>Oscar Wilde</footer></blockquote>",
  },
  {
    q: "Becoming a great leader doesn't mean being perfect. it means living with your imperfections.",
    a: "Lolly Daskal",
    c: "92",
    h: "<blockquote>&ldquo;Becoming a great leader doesn't mean being perfect. it means living with your imperfections.&rdquo; &mdash; <footer>Lolly Daskal</footer></blockquote>",
  },
  {
    q: "A leader is best when people barely know he exists, when his work is done, his aim fulfilled, they will say: we did it ourselves.",
    a: "Lao Tzu",
    c: "129",
    h: "<blockquote>&ldquo;A leader is best when people barely know he exists, when his work is done, his aim fulfilled, they will say: we did it ourselves.&rdquo; &mdash; <footer>Lao Tzu</footer></blockquote>",
  },
  {
    q: "Ability is a poor man's wealth.",
    a: "John Wooden",
    c: "31",
    h: "<blockquote>&ldquo;Ability is a poor man's wealth.&rdquo; &mdash; <footer>John Wooden</footer></blockquote>",
  },
  {
    q: "You can tell more about a person by what he says about others than you can by what others say about him.",
    a: "Audrey Hepburn",
    c: "104",
    h: "<blockquote>&ldquo;You can tell more about a person by what he says about others than you can by what others say about him.&rdquo; &mdash; <footer>Audrey Hepburn</footer></blockquote>",
  },
  {
    q: "The first step toward getting somewhere is to decide that you are not going to stay where you are.",
    a: "Unknown",
    c: "98",
    h: "<blockquote>&ldquo;The first step toward getting somewhere is to decide that you are not going to stay where you are.&rdquo; &mdash; <footer>Unknown</footer></blockquote>",
  },
  {
    q: "Time is a game played beautifully by children.",
    a: "Heraclitus",
    c: "46",
    h: "<blockquote>&ldquo;Time is a game played beautifully by children.&rdquo; &mdash; <footer>Heraclitus</footer></blockquote>",
  },
  {
    q: "At the center of your being you have the answer; you know who you are and you know what you want.",
    a: "Lao Tzu",
    c: "97",
    h: "<blockquote>&ldquo;At the center of your being you have the answer; you know who you are and you know what you want.&rdquo; &mdash; <footer>Lao Tzu</footer></blockquote>",
  },
  {
    q: "Each time we don't say what we wanna say, we're dying.",
    a: "Yoko Ono",
    c: "54",
    h: "<blockquote>&ldquo;Each time we don't say what we wanna say, we're dying.&rdquo; &mdash; <footer>Yoko Ono</footer></blockquote>",
  },
  {
    q: "Ancient Rule of Twenty-one: if you do anything for twenty-one days in a row, it will be installed as a habit.",
    a: "Robin Sharma",
    c: "109",
    h: "<blockquote>&ldquo;Ancient Rule of Twenty-one: if you do anything for twenty-one days in a row, it will be installed as a habit.&rdquo; &mdash; <footer>Robin Sharma</footer></blockquote>",
  },
  {
    q: "Imagination is everything. It is the preview of life's coming attractions.",
    a: "Albert Einstein",
    c: "74",
    h: "<blockquote>&ldquo;Imagination is everything. It is the preview of life's coming attractions.&rdquo; &mdash; <footer>Albert Einstein</footer></blockquote>",
  },
  {
    q: "No one can confidently say that he will still be living tomorrow.",
    a: "Euripides",
    c: "65",
    h: "<blockquote>&ldquo;No one can confidently say that he will still be living tomorrow.&rdquo; &mdash; <footer>Euripides</footer></blockquote>",
  },
];
